### ISSUE TITLE
Where can I find the excat model architecture?

### ISSUE THREAD

**Issue by Flajt** [xiaoyuin/tntspa#3]
Hello, 
I want to use your model in a small university project of mine (of course with proper citation).
If I got everything correct, the model was trained with the fairseq command line tool. 
I would like to use it in a python script which I can call upon in my code.
Unfortunately, I haven't been able to get your model checkpoint to work with the ConS2S model from pytorch hub, because some keys are missing. If I'm not wrong there is some kind of architecture mentioned in your paper, but I can't figure out the exact details on how to remodel it so I could use your checkpoint (might be because I'm rather new to all this, so apologies for that). So I would like to ask if you could tell me how your model structure looks like e.g. in pytorch (or whatever you would prefer)?

**Comment by xiaoyuin** [comment]
Hi @Flajt,

Thanks for your interest in my project!

Yes, ConvS2S model was trained with the `fairseq` framework. I'm not sure if the "fairseq command line tool" you mentioned is the same as the one I used. I also didn't use the model from pytorch hub so I guess my checkpoint is not compatible with whatever is there. I'm also not sure if the latest `fairseq` still contains my models or not, if you really wanna reproduce, maybe use the snapshot git submodule I saved in the repository. I'm sure you know what git submodule is, and if you do, you'll be smart enough to figure out this commit of `fairseq` was the one I used before for all the training and testing:

![Screenshot 2020-11-30 at 14 19 57](https://user-images.githubusercontent.com/9080785/100615015-4a5ff880-3317-11eb-8e9e-836f458dc83a.png)


In terms of the details of my training and my checkpoint, maybe you can take a look at:
- training script I used to train convS2S models on hpc (high-performance-computing) servers: [hpc_train_fairseq_fconv.sh](https://github.com/xiaoyuin/tntspa/blob/master/scripts/hpc_train_fairseq_fconv.sh)
- test script I used on my local mac to test the convS2S model: [test_fairseq.sh](https://github.com/xiaoyuin/tntspa/blob/master/scripts/test_fairseq.sh)

There are also other scripts in the `scripts/` folder. Of course, these scripts may not run directly due to differences in the host machine, especially the hpc scripts. But you may be able to see some hyperparameters I used from within the scripts, like: 
```
srun python3 fairseq/train.py $DDIR/fairseq-data-bin -s en -t sparql \
--lr 0.5 --clip-norm 0.1 --dropout 0.2 --max-tokens 4000 \
--criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
--arch fconv_wmt_en_de --lr-scheduler fixed --force-anneal 50 \
--max-epoch 500 --save-interval 100 --valid-subset valid,test \
--save-dir $MDIR/fairseq_fconv_wmt_en_de
```

`srun` is a function on hpc server, `$DDIR/fairseq-data-bin` is the data folder you may find [here in the google drive](https://drive.google.com/drive/folders/1Ix9K7ZQMierwS9AvFNxVDDD_8edQ5x1F?usp=sharing), I'm sure you must already know why there's a `fairseq-data-bin` folder in each dataset if you read my README thoroughly.

I'm sorry that this whole thing is not very straightforward to do. That's the best I can help you, hope you enjoy exploring stuff! :)

**Comment by Flajt** [comment]
Thank you for the fast reply, I thought it's more of a command line tool than a normal library to import.
That with the sub module was helpful, I'm now checking that out.

**Comment by Flajt** [comment]
I got the model implemented: I installed fairseq 0.7.2 via pip and used some code from the fairseq submodule in your repository, so again thanks for that tip with the submodule. I might raise a different issue regarding another question but so far I'm good. If you are interested on what I'm doing you can check out my repository called Veritas. Anyway thaks for the help.

**Comment by xiaoyuin** [comment]
Good to hear! Of course, you're welcomed to open any other issues you may have, although I may not be able to respond to them quickly, sorry about that.

**Comment by heraclex12** [comment]
Hi @xiaoyuin

I tried to run your fairseq_fconv script, but it stopped after 53 epochs and didn't export any checkpoint. However, I trained LSTM and transformer model and it ok. What the happened to me?

**Comment by xiaoyuin** [comment]
@heraclex12 There can be many reasons. I cannot say for sure which situation you were in. But I suggest you go check into the code or documentation of `fairseq` to figure out what those parameters in the script mean, like `--save-interval 100` if I remember correctly means it will save checkpoint for every 100 epochs, maybe the reason why your training didn't output any checkpoint. I think there are also some parameters that will control whether the training can be ended earlier than the max epochs. After you know these parameters, you can configure them differently to suit your needs, rather than only run my scripts, because I tailored those scripts according to my needs.

Above is just my guessing, you should debug depending on what errors or outputs you got in the terminal, try to search in the stackoverflow, github repository of `fairseq`, or relevant places.
